[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "images/voxelforge.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  
[[params.ananke_socials]]
name = "minetest"
url = "https://content.minetest.net/users/VoxelForge"
